// UI copy for the "game night" redesign, one block per language.
// Templates use {n} / {i} / {k} placeholders; fill them with fmt().

export const fmt = (s, vars = {}) => s.replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ''));

// "{n} cards" with the right plural form (1 card / 2 karty / 5 kart).
export function cards(s, n) {
  if (n === 1 && s.cardsOne) return s.cardsOne;
  const few = n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14);
  if (few && s.cardsFew) return fmt(s.cardsFew, { n });
  return fmt(s.cardsCount, { n });
}

export const GAME_STRINGS = {
  en: {
    heroLine: "One phone. Everyone talks.",
    questionsCount: '{n} QUESTIONS',
    decks: 'Decks', spice: 'Spice', saved: 'Saved',
    allDecks: 'All {n}', pickedDecks: '{n} picked', cardsOne: '1 card', cardsCount: '{n} cards', cardsOf: '{n} of {total} cards',
    start: 'START',
    navPlay: 'play', navSaved: 'saved', navLoved: 'loved', navSay: 'say',
    cardOf: 'Card {i} of {n}', fullDeck: 'FULL DECK', all: 'ALL',
    catsPicked: '{k} CATEGORIES', catsMeta: '{k} CATEGORIES · {n} CARDS', catMeta: '1 CATEGORY · {n} CARDS',
    next: 'NEXT', undoSkip: 'UNDO SKIP', skipped: 'SKIPPED',
    startingOver: 'STARTING OVER · RESHUFFLED',
    savedToast: 'Saved', undo: 'UNDO',
    allCards: 'All cards',
    makeOwn: 'Make your own cards', soon: 'SOON',
    decksTitle: 'Decks', clear: 'Clear', decksNote: "Pick nothing to play the full deck of {n}.",
    playN: 'PLAY {n} CARDS', moreDecks: '+{n} more', morePicked: '{n} picked', moreTitle: 'More decks',
    adultTag: '18+ SUGGESTED', optInTag: 'NOT IN ALL',
    spiceTitle: 'How spicy tonight?', spiceNote: 'Only changes the Spicy deck. Nothing is locked.',
    mild: 'Mild', spicy: 'Spicy', nomercy: 'No mercy',
    timer: 'Timer per card', timerBadge: '{n} SEC', timeUp: "TIME'S UP", done: 'DONE',
    roundDone: 'ROUND DONE', wholeDeck: "That's the whole deck.",
    played: 'PLAYED', skippedStat: 'SKIPPED', starred: 'STARRED',
    again: 'SHUFFLE & GO AGAIN', otherDecks: 'OTHER DECKS', seeStarred: 'SEE {n} STARRED',
    savedTitle: 'Saved', savedHint: 'star one mid-game', savedOn: 'SAVED {date}',
    emptyTitle: 'Nothing saved yet', emptyText: 'Tap ★ on a card mid-game and it lands here, ready to replay or share.', startRound: 'START A ROUND',
    lovedTitle: 'Most loved', lovedSub: 'What everyone else keeps starring', allTime: 'ALL TIME',
    lovedEmpty: 'The ranking fills in once enough tables have played. Our picks until then:', editorsPick: "EDITOR'S PICK",
    ariaShare: 'Share this card',
    shareTitle: 'Share this one', fromSaved: 'FROM SAVED', fmtLink: 'Link', surface: 'Card surface',
    story: 'STORY', post: 'POST', sendT: 'SEND', linkT: 'LINK', saveImage: 'SAVE IMAGE', copyLink: 'COPY LINK',
    copied: 'COPIED ✓', imageSaved: 'SAVED ✓', shareFailed: "Couldn't share. Try Save image instead.",
    sayTitle: 'Say something', saySub: "An idea to make it better, or something that's broken.",
    typeQuestion: 'NEW QUESTION', typeIdea: 'IDEA', typeBug: 'BUG',
    phQuestion: 'Your question…', phIdea: 'What would make it better?', phBug: 'What went wrong?',
    whichDeck: 'Which deck?', anyDeck: 'Any', sayNote: "We read every one.",
    sending: 'SENDING…', sentLabel: 'SENT ✓', thanks: 'Got it. Thank you.', sentNote: "We read every one.",
    backToPlaying: 'BACK TO PLAYING', sendAnother: 'SEND ANOTHER',
    failTitle: "Didn't go through", failOffline: "You look offline. Your text is saved, so try again when you're back online.",
    failLimit: "One suggestion per day. Your text is saved, so try again tomorrow.", failServer: "Something went wrong on our side. Your text is saved, so try again in a moment.", tryAgain: 'TRY AGAIN',
    obSkip: 'Skip',
    obExample: 'EXAMPLE', obHowCard: 'Read it out loud. Everyone answers.',
    obHowTap: 'Tap the card to flip to the next one.', obHowNext: 'Pass the phone, draw the next card.', obHowStar: 'Star the good ones to find them later.',
    obHowSkip: "Skip anything that doesn't fit the room.", obGotIt: 'GOT IT',
    obWhoTitle: "Who's at the table tonight?", obWhoSub: "We'll suggest decks that fit. Pick all that apply.",
    whoFriends: 'Friends', whoDate: 'A date', whoFamily: 'Family', whoWork: 'Work team', startPlaying: 'START PLAYING',
    installTitle: 'Keep Tralala on your phone', installSub: 'Opens in one tap, straight from your home screen.',
    installStep1: 'Tap Share {icon} in Safari', installStep2: 'Choose “Add to Home Screen”',
    notNow: 'NOT NOW', install: 'INSTALL', ok: 'OK',
    boardTitle: "WHAT OTHERS SAID", boardEmpty: "No suggestions yet. Be the first. A few ideas to start with:", exampleTag: "EXAMPLE", ariaVoteUp: "Upvote", ariaVoteDown: "Downvote", sendBtn: "SEND",
    navInstall: "install", installMenu1: "Open the browser menu {icon}", installMenu2: "Choose “Add to Home screen” or “Install app”",
    heroSub: "Conversation questions for friends, couples and teams.", trustLine: "Free · No sign-up", continueAt: "CONTINUE · CARD {i} OF {n}",
    langTitle: 'Language', langNote: "Switch any time. The card changes right away.",
    ariaHome: "Tralala, go to start", ariaClose: 'Close', ariaBack: 'Back', ariaUndo: 'Undo skip', ariaSkip: 'Skip this card',
    ariaSave: 'Save this card', ariaUnsave: 'Remove from saved', ariaLang: 'Change language',
  },
  lt: {
    heroLine: "Vienas telefonas. Kalbasi visi.",
    questionsCount: '{n} KLAUSIMŲ',
    decks: 'Kaladės', spice: 'Aštrumas', saved: 'Išsaugoti',
    allDecks: 'Visos {n}', pickedDecks: 'Pasirinkta {n}', cardsOne: '1 kort.', cardsCount: '{n} kort.', cardsOf: '{n} iš {total} kort.',
    start: 'PRADĖTI',
    navPlay: 'žaisti', navSaved: 'išsaugoti', navLoved: 'mėgstami', navSay: 'sakyk',
    cardOf: 'Kortelė {i} iš {n}', fullDeck: 'VISA KALADĖ', all: 'VISOS',
    catsPicked: '{k} KATEGORIJOS', catsMeta: '{k} KATEGORIJOS · {n} KORT.', catMeta: '1 KATEGORIJA · {n} KORT.',
    next: 'KITA', undoSkip: 'ATŠAUKTI', skipped: 'PRALEISTA',
    startingOver: 'IŠ NAUJO · SUMAIŠYTA',
    savedToast: 'Išsaugota', undo: 'ATŠAUKTI',
    allCards: 'Visos kortelės',
    makeOwn: 'Susikurk savo korteles', soon: 'NETRUKUS',
    decksTitle: 'Kaladės', clear: 'Išvalyti', decksNote: "Nieko nepasirinkus žaidžiama visa kaladė, visi {n}.",
    playN: 'ŽAISTI {n} KORT.', moreDecks: 'Dar +{n}', morePicked: 'Pasirinkta {n}', moreTitle: 'Daugiau kaladžių',
    adultTag: 'SIŪLOMA 18+', optInTag: 'NE Į „VISOS“',
    spiceTitle: 'Kiek aštriai šįvakar?', spiceNote: 'Keičia tik „Aštrūs“ kaladę. Niekas neužrakinta.',
    mild: 'Švelniai', spicy: 'Aštriai', nomercy: 'Be gailesčio',
    timer: 'Laikmatis kortelei', timerBadge: '{n} SEK.', timeUp: 'LAIKAS!', done: 'GERAI',
    roundDone: 'RATAS BAIGTAS', wholeDeck: 'Tai visa kaladė.',
    played: 'SUŽAISTA', skippedStat: 'PRALEISTA', starred: 'SU ★',
    again: 'MAIŠYTI IR IŠ NAUJO', otherDecks: 'KITOS KALADĖS', seeStarred: 'ŽIŪRĖTI {n} ★',
    savedTitle: 'Išsaugoti', savedHint: 'žymėk ★ žaidimo metu', savedOn: 'IŠSAUGOTA {date}',
    emptyTitle: 'Kol kas nieko', emptyText: "Žaidimo metu bakstelėk ★ ant kortelės, ir ji atsidurs čia. Galėsi prie jos grįžti arba ja pasidalinti.", startRound: 'PRADĖTI RATĄ',
    lovedTitle: 'Mėgstamiausi', lovedSub: 'Ką kiti žymi žvaigždute dažniausiai', allTime: 'VISŲ LAIKŲ',
    lovedEmpty: "Reitingas atsiras, kai pažais daugiau kompanijų. Kol kas rodome mūsų pasirinktus:", editorsPick: 'MŪSŲ PASIRINKIMAS',
    ariaShare: 'Dalintis kortele',
    shareTitle: 'Pasidalink', fromSaved: 'IŠ IŠSAUGOTŲ', fmtLink: 'Nuoroda', surface: 'Kortelės spalva',
    story: 'STORY', post: 'ĮRAŠAS', sendT: 'SIŲSTI', linkT: 'NUORODA', saveImage: 'IŠSAUGOTI VAIZDĄ', copyLink: 'KOPIJUOTI NUORODĄ',
    copied: 'NUKOPIJUOTA ✓', imageSaved: 'IŠSAUGOTA ✓', shareFailed: "Nepavyko pasidalinti. Išsaugok vaizdą.",
    sayTitle: 'Pasakyk', saySub: "Idėja, kaip padaryti geriau, arba kas nors neveikia.",
    typeQuestion: 'NAUJAS KLAUSIMAS', typeIdea: 'IDĖJA', typeBug: 'KLAIDA',
    phQuestion: 'Tavo klausimas…', phIdea: 'Kas padarytų geriau?', phBug: 'Kas nepavyko?',
    whichDeck: 'Kuriai kaladei?', anyDeck: 'Bet kuriai', sayNote: "Perskaitome kiekvieną.",
    sending: 'SIUNČIAMA…', sentLabel: 'IŠSIŲSTA ✓', thanks: 'Gavom. Ačiū.', sentNote: "Perskaitome kiekvieną.",
    backToPlaying: 'GRĮŽTI Į ŽAIDIMĄ', sendAnother: 'SIŲSTI DAR VIENĄ',
    failTitle: 'Nepavyko išsiųsti', failOffline: "Atrodo, nėra interneto. Tekstas išsaugotas, bandyk, kai grįš ryšys.",
    failLimit: "Vienas pasiūlymas per dieną. Tekstas išsaugotas, bandyk rytoj.", failServer: "Kažkas nepavyko mūsų pusėje. Tekstas išsaugotas, pabandyk po minutės.", tryAgain: 'BANDYTI DAR KARTĄ',
    obSkip: 'Praleisti',
    obExample: 'PAVYZDYS', obHowCard: 'Perskaityk garsiai. Atsako visi.',
    obHowTap: 'Bakstelėk kortelę ir ji apsivers į kitą.', obHowNext: 'Perduok telefoną ir trauk kitą kortelę.', obHowStar: 'Pažymėk gerus ★, kad vėliau rastum.',
    obHowSkip: 'Praleisk, kas netinka kompanijai.', obGotIt: 'AIŠKU',
    obWhoTitle: 'Kas šiandien prie stalo?', obWhoSub: 'Pasiūlysime tinkamas kalades. Rinkis kelis.',
    whoFriends: 'Draugai', whoDate: 'Pasimatymas', whoFamily: 'Šeima', whoWork: 'Kolegos', startPlaying: 'PRADĖTI ŽAISTI',
    installTitle: 'Laikyk Tralala telefone', installSub: 'Atsidaro vienu bakstelėjimu iš pradžios ekrano.',
    installStep1: 'Safari bakstelėk Bendrinti {icon}', installStep2: 'Pasirink „Įtraukti į pradžios ekraną“',
    notNow: 'NE DABAR', install: 'ĮDIEGTI', ok: 'GERAI',
    boardTitle: "KĄ PASAKĖ KITI", boardEmpty: "Dar nieko nėra, būk pirmas. Kelios idėjos pradžiai:", exampleTag: "PAVYZDYS", ariaVoteUp: "Balsuoti už", ariaVoteDown: "Balsuoti prieš", sendBtn: "SIŲSTI",
    navInstall: "įdiegti", installMenu1: "Atidaryk naršyklės meniu {icon}", installMenu2: "Pasirink „Įtraukti į pradžios ekraną“ arba „Įdiegti programą“",
    heroSub: "Klausimai pokalbiams su draugais, pora ar komanda.", trustLine: "Nemokama · Be registracijos", continueAt: "TĘSTI · KORTELĖ {i} IŠ {n}",
    langTitle: 'Kalba', langNote: "Keisk bet kada, kortelė pasikeis iškart.",
    ariaHome: "Tralala, į pradžią", ariaClose: 'Uždaryti', ariaBack: 'Atgal', ariaUndo: 'Atšaukti praleidimą', ariaSkip: 'Praleisti kortelę',
    ariaSave: 'Išsaugoti kortelę', ariaUnsave: 'Pašalinti iš išsaugotų', ariaLang: 'Keisti kalbą',
  },
  de: {
    heroLine: "Ein Handy. Alle reden.",
    questionsCount: '{n} FRAGEN',
    decks: 'Decks', spice: 'Schärfe', saved: 'Gespeichert',
    allDecks: 'Alle {n}', pickedDecks: '{n} gewählt', cardsOne: '1 Karte', cardsCount: '{n} Karten', cardsOf: '{n} von {total} Karten',
    start: 'START',
    navPlay: 'spielen', navSaved: 'gespeichert', navLoved: 'beliebt', navSay: "sag's",
    cardOf: 'Karte {i} von {n}', fullDeck: 'GANZES DECK', all: 'ALLE',
    catsPicked: '{k} KATEGORIEN', catsMeta: '{k} KATEGORIEN · {n} KARTEN', catMeta: '1 KATEGORIE · {n} KARTEN',
    next: 'WEITER', undoSkip: 'RÜCKGÄNGIG', skipped: 'ÜBERSPRUNGEN',
    startingOver: 'VON VORN · NEU GEMISCHT',
    savedToast: 'Gespeichert', undo: 'RÜCKGÄNGIG',
    allCards: 'Alle Karten',
    makeOwn: 'Eigene Karten erstellen', soon: 'BALD',
    decksTitle: 'Decks', clear: 'Leeren', decksNote: "Nichts gewählt heißt: das ganze Deck, alle {n}.",
    playN: '{n} KARTEN SPIELEN', moreDecks: '+{n} mehr', morePicked: '{n} gewählt', moreTitle: 'Weitere Decks',
    adultTag: '18+ EMPFOHLEN', optInTag: 'NICHT IN ALLE',
    spiceTitle: 'Wie scharf heute?', spiceNote: 'Ändert nur das Deck „Pikant“. Nichts ist gesperrt.',
    mild: 'Mild', spicy: 'Scharf', nomercy: 'Gnadenlos',
    timer: 'Timer pro Karte', timerBadge: '{n} SEK', timeUp: 'ZEIT UM', done: 'FERTIG',
    roundDone: 'RUNDE VORBEI', wholeDeck: 'Das war das ganze Deck.',
    played: 'GESPIELT', skippedStat: 'ÜBERSPRUNGEN', starred: 'MIT ★',
    again: 'MISCHEN & NOCHMAL', otherDecks: 'ANDERE DECKS', seeStarred: '{n} MIT ★ ANSEHEN',
    savedTitle: 'Gespeichert', savedHint: 'markiere eine mit ★ im Spiel', savedOn: 'GESPEICHERT {date}',
    emptyTitle: 'Noch nichts gespeichert', emptyText: "Tippe im Spiel auf ★, dann landet die Karte hier. Du kannst sie später nochmal spielen oder teilen.", startRound: 'RUNDE STARTEN',
    lovedTitle: 'Am beliebtesten', lovedSub: 'Was alle anderen am häufigsten markieren', allTime: 'ALLE ZEIT',
    lovedEmpty: 'Das Ranking füllt sich, sobald genug Runden gespielt wurden. Bis dahin unsere Auswahl:', editorsPick: 'UNSERE WAHL',
    ariaShare: 'Karte teilen',
    shareTitle: 'Diese teilen', fromSaved: 'AUS GESPEICHERT', fmtLink: 'Link', surface: 'Kartenfarbe',
    story: 'STORY', post: 'POST', sendT: 'SENDEN', linkT: 'LINK', saveImage: 'BILD SPEICHERN', copyLink: 'LINK KOPIEREN',
    copied: 'KOPIERT ✓', imageSaved: 'GESPEICHERT ✓', shareFailed: "Teilen ging nicht. Speichere das Bild.",
    sayTitle: "Sag's uns", saySub: "Eine Idee, wie es besser wird, oder etwas, das nicht funktioniert.",
    typeQuestion: 'NEUE FRAGE', typeIdea: 'IDEE', typeBug: 'FEHLER',
    phQuestion: 'Deine Frage…', phIdea: 'Was würde es besser machen?', phBug: 'Was ist schiefgelaufen?',
    whichDeck: 'Welches Deck?', anyDeck: 'Egal', sayNote: "Wir lesen jede Nachricht.",
    sending: 'WIRD GESENDET…', sentLabel: 'GESENDET ✓', thanks: 'Verstanden. Danke.', sentNote: "Wir lesen jede Nachricht.",
    backToPlaying: 'WEITERSPIELEN', sendAnother: 'NOCH EINE SENDEN',
    failTitle: 'Nicht gesendet', failOffline: "Du scheinst offline zu sein. Dein Text bleibt gespeichert, versuch es gleich nochmal.",
    failLimit: "Ein Vorschlag pro Tag. Dein Text bleibt gespeichert, versuch es morgen.", failServer: "Bei uns ist etwas schiefgelaufen. Dein Text bleibt gespeichert, versuch es gleich nochmal.", tryAgain: 'NOCHMAL VERSUCHEN',
    obSkip: 'Überspringen',
    obExample: 'BEISPIEL', obHowCard: 'Lies sie laut vor. Alle antworten.',
    obHowTap: 'Tippe auf die Karte, um zur nächsten umzudrehen.', obHowNext: 'Gib das Handy weiter, zieh die nächste Karte.', obHowStar: 'Markiere die guten mit ★, um sie wiederzufinden.',
    obHowSkip: 'Überspring alles, was nicht zur Runde passt.', obGotIt: 'VERSTANDEN',
    obWhoTitle: 'Wer sitzt heute am Tisch?', obWhoSub: 'Wir schlagen passende Decks vor. Wähle alles Passende.',
    whoFriends: 'Freunde', whoDate: 'Ein Date', whoFamily: 'Familie', whoWork: 'Kollegen', startPlaying: 'LOSSPIELEN',
    installTitle: 'Tralala aufs Handy', installSub: 'Öffnet mit einem Tipp direkt vom Homescreen.',
    installStep1: 'Tippe in Safari auf Teilen {icon}', installStep2: 'Wähle „Zum Home-Bildschirm“',
    notNow: 'NICHT JETZT', install: 'INSTALLIEREN', ok: 'OK',
    boardTitle: "WAS ANDERE SAGTEN", boardEmpty: "Noch keine Vorschläge. Sei der oder die Erste. Ein paar Ideen zum Start:", exampleTag: "BEISPIEL", ariaVoteUp: "Positiv bewerten", ariaVoteDown: "Negativ bewerten", sendBtn: "SENDEN",
    navInstall: "installieren", installMenu1: "Öffne das Browsermenü {icon}", installMenu2: "Wähle „Zum Startbildschirm hinzufügen“ oder „App installieren“",
    heroSub: "Gesprächsfragen für Freunde, Paare und Teams.", trustLine: "Kostenlos · Ohne Anmeldung", continueAt: "WEITER · KARTE {i} VON {n}",
    langTitle: 'Sprache', langNote: "Jederzeit wechseln. Die Karte ändert sich sofort.",
    ariaHome: "Tralala, zur Startseite", ariaClose: 'Schließen', ariaBack: 'Zurück', ariaUndo: 'Überspringen rückgängig', ariaSkip: 'Karte überspringen',
    ariaSave: 'Karte speichern', ariaUnsave: 'Aus Gespeichert entfernen', ariaLang: 'Sprache ändern',
  },
  es: {
    heroLine: "Un móvil. Todos hablan.",
    questionsCount: '{n} PREGUNTAS',
    decks: 'Barajas', spice: 'Picante', saved: 'Guardadas',
    allDecks: 'Todas {n}', pickedDecks: '{n} elegidas', cardsOne: '1 carta', cardsCount: '{n} cartas', cardsOf: '{n} de {total} cartas',
    start: 'EMPEZAR',
    navPlay: 'jugar', navSaved: 'guardadas', navLoved: 'queridas', navSay: 'habla',
    cardOf: 'Carta {i} de {n}', fullDeck: 'BARAJA COMPLETA', all: 'TODAS',
    catsPicked: '{k} CATEGORÍAS', catsMeta: '{k} CATEGORÍAS · {n} CARTAS', catMeta: '1 CATEGORÍA · {n} CARTAS',
    next: 'SIGUIENTE', undoSkip: 'DESHACER', skipped: 'SALTADA',
    startingOver: 'DE NUEVO · MEZCLADA',
    savedToast: 'Guardada', undo: 'DESHACER',
    allCards: 'Todas las cartas',
    makeOwn: 'Crea tus propias cartas', soon: 'PRONTO',
    decksTitle: 'Barajas', clear: 'Borrar', decksNote: "Si no eliges nada, juegas la baraja completa, las {n}.",
    playN: 'JUGAR {n} CARTAS', moreDecks: '+{n} más', morePicked: '{n} elegidas', moreTitle: 'Más barajas',
    adultTag: '18+ SUGERIDO', optInTag: 'NO EN TODAS',
    spiceTitle: '¿Cuánto picante esta noche?', spiceNote: 'Solo cambia la baraja Picantes. Nada está bloqueado.',
    mild: 'Suave', spicy: 'Picante', nomercy: 'Sin piedad',
    timer: 'Temporizador por carta', timerBadge: '{n} SEG', timeUp: '¡TIEMPO!', done: 'LISTO',
    roundDone: 'RONDA TERMINADA', wholeDeck: 'Esa era toda la baraja.',
    played: 'JUGADAS', skippedStat: 'SALTADAS', starred: 'CON ★',
    again: 'MEZCLAR Y OTRA VEZ', otherDecks: 'OTRAS BARAJAS', seeStarred: 'VER {n} CON ★',
    savedTitle: 'Guardadas', savedHint: 'marca una con ★ al jugar', savedOn: 'GUARDADA {date}',
    emptyTitle: 'Nada guardado aún', emptyText: 'Toca ★ en una carta mientras juegas y aparecerá aquí, lista para repetir o compartir.', startRound: 'EMPEZAR RONDA',
    lovedTitle: 'Las más queridas', lovedSub: 'Lo que todos los demás marcan con ★', allTime: 'DE SIEMPRE',
    lovedEmpty: 'El ranking se llena cuando juegan suficientes grupos. Hasta entonces, nuestra selección:', editorsPick: 'NUESTRA ELECCIÓN',
    ariaShare: 'Compartir carta',
    shareTitle: 'Comparte esta', fromSaved: 'DE GUARDADAS', fmtLink: 'Enlace', surface: 'Color de carta',
    story: 'HISTORIA', post: 'POST', sendT: 'ENVIAR', linkT: 'ENLACE', saveImage: 'GUARDAR IMAGEN', copyLink: 'COPIAR ENLACE',
    copied: 'COPIADO ✓', imageSaved: 'GUARDADA ✓', shareFailed: 'No se pudo compartir: guarda la imagen.',
    sayTitle: 'Cuéntanos', saySub: "Una idea para mejorarlo o algo que no funciona.",
    typeQuestion: 'NUEVA PREGUNTA', typeIdea: 'IDEA', typeBug: 'ERROR',
    phQuestion: 'Tu pregunta…', phIdea: '¿Qué lo haría mejor?', phBug: '¿Qué salió mal?',
    whichDeck: '¿Qué baraja?', anyDeck: 'Cualquiera', sayNote: "Leemos cada una.",
    sending: 'ENVIANDO…', sentLabel: 'ENVIADO ✓', thanks: 'Recibido. Gracias.', sentNote: "Leemos cada una.",
    backToPlaying: 'VOLVER A JUGAR', sendAnother: 'ENVIAR OTRA',
    failTitle: 'No se envió', failOffline: 'Parece que no hay conexión. Tu texto se guarda: inténtalo al volver.',
    failLimit: 'Una sugerencia por día. Tu texto se guarda: inténtalo mañana.', failServer: 'Algo falló de nuestro lado. Tu texto se guarda: inténtalo en un rato.', tryAgain: 'REINTENTAR',
    obSkip: 'Saltar',
    obExample: 'EJEMPLO', obHowCard: 'Léela en voz alta. Todos responden.',
    obHowTap: 'Toca la carta para darle la vuelta y pasar a la siguiente.', obHowNext: 'Pasa el móvil y saca la siguiente carta.', obHowStar: 'Marca las buenas con ★ para encontrarlas luego.',
    obHowSkip: 'Salta lo que no encaje con el grupo.', obGotIt: 'ENTENDIDO',
    obWhoTitle: '¿Quién está en la mesa hoy?', obWhoSub: 'Te sugerimos barajas que encajen. Elige todas las que apliquen.',
    whoFriends: 'Amigos', whoDate: 'Una cita', whoFamily: 'Familia', whoWork: 'Compañeros', startPlaying: 'A JUGAR',
    installTitle: 'Ten Tralala en tu móvil', installSub: 'Se abre con un toque desde la pantalla de inicio.',
    installStep1: 'En Safari toca Compartir {icon}', installStep2: 'Elige «Añadir a pantalla de inicio»',
    notNow: 'AHORA NO', install: 'INSTALAR', ok: 'OK',
    boardTitle: "LO QUE OTROS DIJERON", boardEmpty: "Aún no hay sugerencias. Sé el primero. Algunas ideas para empezar:", exampleTag: "EJEMPLO", ariaVoteUp: "Votar a favor", ariaVoteDown: "Votar en contra", sendBtn: "ENVIAR",
    navInstall: "instalar", installMenu1: "Abre el menú del navegador {icon}", installMenu2: "Elige «Añadir a pantalla de inicio» o «Instalar app»",
    heroSub: "Preguntas para conversar con amigos, en pareja o en equipo.", trustLine: "Gratis · Sin registro", continueAt: "SEGUIR · CARTA {i} DE {n}",
    langTitle: 'Idioma', langNote: "Cámbialo cuando quieras. La carta cambia al instante.",
    ariaHome: "Tralala, ir al inicio", ariaClose: 'Cerrar', ariaBack: 'Atrás', ariaUndo: 'Deshacer salto', ariaSkip: 'Saltar esta carta',
    ariaSave: 'Guardar esta carta', ariaUnsave: 'Quitar de guardadas', ariaLang: 'Cambiar idioma',
  },
  it: {
    heroLine: "Un telefono. Parlano tutti.",
    questionsCount: '{n} DOMANDE',
    decks: 'Mazzi', spice: 'Piccante', saved: 'Salvate',
    allDecks: 'Tutti {n}', pickedDecks: '{n} scelti', cardsOne: '1 carta', cardsCount: '{n} carte', cardsOf: '{n} di {total} carte',
    start: 'INIZIA',
    navPlay: 'gioca', navSaved: 'salvate', navLoved: 'amate', navSay: 'dillo',
    cardOf: 'Carta {i} di {n}', fullDeck: 'MAZZO COMPLETO', all: 'TUTTE',
    catsPicked: '{k} CATEGORIE', catsMeta: '{k} CATEGORIE · {n} CARTE', catMeta: '1 CATEGORIA · {n} CARTE',
    next: 'AVANTI', undoSkip: 'ANNULLA', skipped: 'SALTATA',
    startingOver: 'DA CAPO · RIMESCOLATO',
    savedToast: 'Salvata', undo: 'ANNULLA',
    allCards: 'Tutte le carte',
    makeOwn: 'Crea le tue carte', soon: 'PRESTO',
    decksTitle: 'Mazzi', clear: 'Azzera', decksNote: "Se non scegli nulla, giochi il mazzo completo, tutte le {n}.",
    playN: 'GIOCA {n} CARTE', moreDecks: '+{n} altri', morePicked: '{n} scelti', moreTitle: 'Altri mazzi',
    adultTag: '18+ CONSIGLIATO', optInTag: 'NON IN TUTTE',
    spiceTitle: 'Quanto piccante stasera?', spiceNote: 'Cambia solo il mazzo Piccanti. Niente è bloccato.',
    mild: 'Leggero', spicy: 'Piccante', nomercy: 'Senza pietà',
    timer: 'Timer per carta', timerBadge: '{n} SEC', timeUp: 'TEMPO!', done: 'FATTO',
    roundDone: 'GIRO FINITO', wholeDeck: 'Questo era tutto il mazzo.',
    played: 'GIOCATE', skippedStat: 'SALTATE', starred: 'CON ★',
    again: 'MESCOLA E RIGIOCA', otherDecks: 'ALTRI MAZZI', seeStarred: 'VEDI {n} CON ★',
    savedTitle: 'Salvate', savedHint: 'segnane una con ★ in gioco', savedOn: 'SALVATA {date}',
    emptyTitle: 'Ancora niente', emptyText: 'Tocca ★ su una carta durante il gioco e la ritrovi qui, pronta da rigiocare o condividere.', startRound: 'INIZIA UN GIRO',
    lovedTitle: 'Le più amate', lovedSub: 'Quelle che tutti segnano con ★', allTime: 'DI SEMPRE',
    lovedEmpty: 'La classifica si riempie quando avranno giocato abbastanza gruppi. Nel frattempo, le nostre scelte:', editorsPick: 'LA NOSTRA SCELTA',
    ariaShare: 'Condividi carta',
    shareTitle: 'Condividi questa', fromSaved: 'DALLE SALVATE', fmtLink: 'Link', surface: 'Colore carta',
    story: 'STORIA', post: 'POST', sendT: 'INVIA', linkT: 'LINK', saveImage: 'SALVA IMMAGINE', copyLink: 'COPIA LINK',
    copied: 'COPIATO ✓', imageSaved: 'SALVATA ✓', shareFailed: 'Condivisione non riuscita: salva l’immagine.',
    sayTitle: 'Dicci', saySub: "Un'idea per migliorarlo o qualcosa che non funziona.",
    typeQuestion: 'NUOVA DOMANDA', typeIdea: 'IDEA', typeBug: 'BUG',
    phQuestion: 'La tua domanda…', phIdea: 'Cosa lo renderebbe migliore?', phBug: 'Cosa è andato storto?',
    whichDeck: 'Quale mazzo?', anyDeck: 'Qualsiasi', sayNote: "Le leggiamo tutte.",
    sending: 'INVIO…', sentLabel: 'INVIATO ✓', thanks: 'Ricevuto. Grazie.', sentNote: "Le leggiamo tutte.",
    backToPlaying: 'TORNA A GIOCARE', sendAnother: 'INVIANE UN ALTRO',
    failTitle: 'Invio non riuscito', failOffline: 'Sembri offline. Il testo resta qui: riprova quando torni online.',
    failLimit: 'Un suggerimento al giorno. Il testo resta qui: riprova domani.', failServer: 'Qualcosa è andato storto da noi. Il testo resta qui: riprova tra poco.', tryAgain: 'RIPROVA',
    obSkip: 'Salta',
    obExample: 'ESEMPIO', obHowCard: 'Leggila ad alta voce. Rispondono tutti.',
    obHowTap: 'Tocca la carta per girarla e passare alla prossima.', obHowNext: 'Passa il telefono, pesca la carta successiva.', obHowStar: 'Segna le migliori con ★ per ritrovarle.',
    obHowSkip: 'Salta ciò che non va bene per il gruppo.', obGotIt: 'CAPITO',
    obWhoTitle: 'Chi c’è al tavolo stasera?', obWhoSub: 'Ti suggeriamo i mazzi giusti. Scegli tutte le opzioni valide.',
    whoFriends: 'Amici', whoDate: 'Un appuntamento', whoFamily: 'Famiglia', whoWork: 'Colleghi', startPlaying: 'INIZIA A GIOCARE',
    installTitle: 'Tieni Tralala sul telefono', installSub: 'Si apre con un tocco dalla schermata Home.',
    installStep1: 'In Safari tocca Condividi {icon}', installStep2: 'Scegli “Aggiungi alla schermata Home”',
    notNow: 'NON ORA', install: 'INSTALLA', ok: 'OK',
    boardTitle: "COSA HANNO DETTO GLI ALTRI", boardEmpty: "Ancora nessun suggerimento. Sii il primo. Qualche idea per iniziare:", exampleTag: "ESEMPIO", ariaVoteUp: "Vota positivamente", ariaVoteDown: "Vota negativamente", sendBtn: "INVIA",
    navInstall: "installa", installMenu1: "Apri il menu del browser {icon}", installMenu2: "Scegli “Aggiungi a schermata Home” o “Installa app”",
    heroSub: "Domande per conversare con amici, in coppia o in team.", trustLine: "Gratis · Senza registrazione", continueAt: "CONTINUA · CARTA {i} DI {n}",
    langTitle: 'Lingua', langNote: "Cambiala quando vuoi. La carta cambia subito.",
    ariaHome: "Tralala, vai all'inizio", ariaClose: 'Chiudi', ariaBack: 'Indietro', ariaUndo: 'Annulla salto', ariaSkip: 'Salta questa carta',
    ariaSave: 'Salva questa carta', ariaUnsave: 'Rimuovi dalle salvate', ariaLang: 'Cambia lingua',
  },
  pl: {
    heroLine: "Jeden telefon. Rozmawiają wszyscy.",
    questionsCount: '{n} PYTAŃ',
    decks: 'Talie', spice: 'Pikanteria', saved: 'Zapisane',
    allDecks: 'Wszystkie {n}', pickedDecks: 'Wybrano {n}', cardsOne: '1 karta', cardsFew: '{n} karty', cardsCount: '{n} kart', cardsOf: '{n} z {total} kart',
    start: 'START',
    navPlay: 'graj', navSaved: 'zapisane', navLoved: 'lubiane', navSay: 'mów',
    cardOf: 'Karta {i} z {n}', fullDeck: 'CAŁA TALIA', all: 'WSZYSTKIE',
    catsPicked: '{k} KATEGORIE', catsMeta: '{k} KATEGORIE · {n} KART', catMeta: '1 KATEGORIA · {n} KART',
    next: 'DALEJ', undoSkip: 'COFNIJ', skipped: 'POMINIĘTA',
    startingOver: 'OD NOWA · PRZETASOWANE',
    savedToast: 'Zapisano', undo: 'COFNIJ',
    allCards: 'Wszystkie karty',
    makeOwn: 'Stwórz własne karty', soon: 'WKRÓTCE',
    decksTitle: 'Talie', clear: 'Wyczyść', decksNote: "Jeśli nic nie wybierzesz, grasz całą talią, wszystkie {n}.",
    playN: 'GRAJ {n} KART', moreDecks: '+{n} więcej', morePicked: 'Wybrano {n}', moreTitle: 'Więcej talii',
    adultTag: 'SUGEROWANE 18+', optInTag: 'NIE W WSZYSTKICH',
    spiceTitle: 'Jak pikantnie dziś?', spiceNote: 'Zmienia tylko talię Pikantne. Nic nie jest zablokowane.',
    mild: 'Łagodnie', spicy: 'Pikantnie', nomercy: 'Bez litości',
    timer: 'Minutnik na kartę', timerBadge: '{n} SEK', timeUp: 'CZAS!', done: 'GOTOWE',
    roundDone: 'RUNDA SKOŃCZONA', wholeDeck: 'To cała talia.',
    played: 'ZAGRANE', skippedStat: 'POMINIĘTE', starred: 'Z ★',
    again: 'TASUJ I JESZCZE RAZ', otherDecks: 'INNE TALIE', seeStarred: 'ZOBACZ {n} Z ★',
    savedTitle: 'Zapisane', savedHint: 'oznacz ★ w trakcie gry', savedOn: 'ZAPISANO {date}',
    emptyTitle: 'Nic jeszcze nie ma', emptyText: "Stuknij ★ na karcie w trakcie gry, a trafi tutaj. Możesz do niej wrócić albo ją udostępnić.", startRound: 'ZACZNIJ RUNDĘ',
    lovedTitle: 'Najbardziej lubiane', lovedSub: 'Co inni najczęściej oznaczają ★', allTime: 'CAŁY CZAS',
    lovedEmpty: 'Ranking wypełni się, gdy zagra więcej grup. Do tego czasu nasz wybór:', editorsPick: 'NASZ WYBÓR',
    ariaShare: 'Udostępnij kartę',
    shareTitle: 'Udostępnij', fromSaved: 'Z ZAPISANYCH', fmtLink: 'Link', surface: 'Kolor karty',
    story: 'STORY', post: 'POST', sendT: 'WYŚLIJ', linkT: 'LINK', saveImage: 'ZAPISZ OBRAZ', copyLink: 'KOPIUJ LINK',
    copied: 'SKOPIOWANO ✓', imageSaved: 'ZAPISANO ✓', shareFailed: "Nie udało się udostępnić. Zapisz obraz.",
    sayTitle: 'Powiedz nam', saySub: "Pomysł, jak to ulepszyć, albo coś, co nie działa.",
    typeQuestion: 'NOWE PYTANIE', typeIdea: 'POMYSŁ', typeBug: 'BŁĄD',
    phQuestion: 'Twoje pytanie…', phIdea: 'Co by to poprawiło?', phBug: 'Co poszło nie tak?',
    whichDeck: 'Która talia?', anyDeck: 'Dowolna', sayNote: "Czytamy każdą wiadomość.",
    sending: 'WYSYŁANIE…', sentLabel: 'WYSŁANO ✓', thanks: 'Mamy to. Dziękujemy.', sentNote: "Czytamy każdą.",
    backToPlaying: 'WRÓĆ DO GRY', sendAnother: 'WYŚLIJ KOLEJNE',
    failTitle: 'Nie wysłano', failOffline: "Wygląda na brak internetu. Tekst zostaje, spróbuj, gdy wróci połączenie.",
    failLimit: "Jedna propozycja dziennie. Tekst zostaje, spróbuj jutro.", failServer: "Coś poszło nie tak po naszej stronie. Tekst zostaje, spróbuj za chwilę.", tryAgain: 'SPRÓBUJ PONOWNIE',
    obSkip: 'Pomiń',
    obExample: 'PRZYKŁAD', obHowCard: 'Przeczytaj na głos. Odpowiadają wszyscy.',
    obHowTap: 'Stuknij kartę, żeby odwrócić ją na następną.', obHowNext: 'Podaj telefon, dobierz kolejną kartę.', obHowStar: 'Oznacz dobre ★, żeby je potem znaleźć.',
    obHowSkip: 'Pomiń to, co nie pasuje do towarzystwa.', obGotIt: 'JASNE',
    obWhoTitle: 'Kto dziś siedzi przy stole?', obWhoSub: 'Podpowiemy pasujące talie. Wybierz wszystko, co pasuje.',
    whoFriends: 'Przyjaciele', whoDate: 'Randka', whoFamily: 'Rodzina', whoWork: 'Współpracownicy', startPlaying: 'ZACZNIJ GRAĆ',
    installTitle: 'Miej Tralala w telefonie', installSub: 'Otwiera się jednym stuknięciem z ekranu głównego.',
    installStep1: 'W Safari stuknij Udostępnij {icon}', installStep2: 'Wybierz „Do ekranu początkowego”',
    notNow: 'NIE TERAZ', install: 'ZAINSTALUJ', ok: 'OK',
    boardTitle: "CO POWIEDZIELI INNI", boardEmpty: "Jeszcze nie ma propozycji. Bądź pierwszy. Kilka pomysłów na start:", exampleTag: "PRZYKŁAD", ariaVoteUp: "Głosuj za", ariaVoteDown: "Głosuj przeciw", sendBtn: "WYŚLIJ",
    navInstall: "zainstaluj", installMenu1: "Otwórz menu przeglądarki {icon}", installMenu2: "Wybierz „Dodaj do ekranu głównego” lub „Zainstaluj aplikację”",
    heroSub: "Pytania do rozmów z przyjaciółmi, w parze i w zespole.", trustLine: "Za darmo · Bez rejestracji", continueAt: "DALEJ · KARTA {i} Z {n}",
    langTitle: 'Język', langNote: "Zmieniaj kiedy chcesz. Karta zmieni się od razu.",
    ariaHome: "Tralala, przejdź na start", ariaClose: 'Zamknij', ariaBack: 'Wstecz', ariaUndo: 'Cofnij pominięcie', ariaSkip: 'Pomiń tę kartę',
    ariaSave: 'Zapisz tę kartę', ariaUnsave: 'Usuń z zapisanych', ariaLang: 'Zmień język',
  },
};
