// Marketing copy for the landing sections below the game (app/LandingContent.jsx,
// app/LandingFooter.jsx). Kept separate from lib/content.js, which is the game's
// own question/UI-string data. Vibe entries are keyed by the same category ids
// as CATEGORIES in lib/content.js.

export const LANDING = {
  en: {
    kicker: 'TRALALA',
    h2Line1: 'Conversation Cards for',
    h2Line2: 'Friends, Couples & Groups',
    lede: "From lighthearted icebreakers to the ones you've never said out loud — find your vibe below.",
    cta: 'Start a Conversation',
    introFine: 'Start free. No account needed.',
    vibesH2: 'Choose Your Vibe',
    vibes: {
      fun: { title: 'Fun Questions', blurb: 'Light, playful prompts for laughs with anyone.' },
      know: { title: 'Icebreaker Questions', blurb: 'Get-to-know-you icebreakers for new faces.' },
      deep: { title: 'Deep Questions', blurb: 'Meaningful questions that go past small talk.' },
      team: { title: 'Team Questions', blurb: 'Icebreakers built for coworkers and teammates.' },
      spicy: { title: 'Spicy Questions', blurb: 'Bold, flirty questions for the brave (18+).' },
      future: { title: 'Future Questions', blurb: 'Dreams, goals and what comes next.' },
      firsts: { title: 'Firsts Questions', blurb: 'Firsts, memories and how it all began.' },
      awkward: { title: 'Awkward Questions', blurb: 'Confessions and stories nobody saw coming.' },
      couples: { title: 'Couples Questions', blurb: 'Built for date night and staying close.' },
      food: { title: 'Food Questions', blurb: 'Cravings, cooking and dinner-table debates.' },
    },
    aboutH2: 'What Is Tralala?',
    aboutP1: "Tralala is a free deck of conversation cards designed to spark real talk — the kind that goes past small talk. Whether you're catching up with old friends, deepening a relationship, breaking the ice at a party, or bonding with your team, Tralala hands you the next question before the silence gets awkward.",
    aboutP2: "Each round deals one question at a time: read it out loud, pass the phone around, and see where the conversation goes. Choose from ten categories — fun, deep, couples, team, icebreakers, spicy (18+), future, firsts, awkward and food — or shuffle everything together for a mixed deck. The deck keeps growing and it's available in six languages, so there's always something new to ask.",
    aboutP3: "There's nothing to install and nothing to sign up for. Tralala runs entirely in your browser, works on any phone, and remembers your favorite questions so you can share them later. Just open the deck, pick your vibe, and start talking.",
    forH2: 'Perfect For',
    perfectFor: ['Friends', 'Couples', 'Parties', 'Date Nights', 'Teams', 'Road Trips'],
    ctaH2: 'Ready to Talk?',
    ctaFine: 'No account. No setup. Just play.',
    footer1: 'Tralala.cards — made for better conversations.',
    footer2: 'Anonymous usage data only — no accounts, no personal data collected.',
    footer3: 'By starting, you agree to anonymous usage data being collected.',
  },

  lt: {
    kicker: 'TRALALA',
    h2Line1: 'Pokalbių kortelės',
    h2Line2: 'draugams, poroms ir grupėms',
    lede: 'Nuo lengvų pažinties klausimų iki tų, kurių niekada nesakei garsiai — susirask savo nuotaiką žemiau.',
    cta: 'Pradėti pokalbį',
    introFine: 'Pradėk nemokamai. Paskyra nereikalinga.',
    vibesH2: 'Pasirink savo nuotaiką',
    vibes: {
      fun: { title: 'Linksmi klausimai', blurb: 'Lengvi, žaismingi klausimai juokui su bet kuo.' },
      know: { title: 'Pažinties klausimai', blurb: 'Pažinties klausimai naujiems veidams.' },
      deep: { title: 'Gilūs klausimai', blurb: 'Prasmingi klausimai, einantys giliau nei buitinis pokalbis.' },
      team: { title: 'Komandos klausimai', blurb: 'Įžanginiai klausimai kolegoms ir komandai.' },
      spicy: { title: 'Aštrūs klausimai (18+)', blurb: 'Drąsūs, flirtuojantys klausimai drąsiems (18+).' },
      future: { title: 'Ateities klausimai', blurb: 'Svajonės, tikslai ir kas laukia toliau.' },
      firsts: { title: 'Pirmų kartų klausimai', blurb: 'Pirmi kartai, prisiminimai ir kaip viskas prasidėjo.' },
      awkward: { title: 'Nejaukūs klausimai', blurb: 'Prisipažinimai ir istorijos, kurių niekas nesitikėjo.' },
      couples: { title: 'Klausimai poroms', blurb: 'Sukurta pasimatymo vakarui ir artumui išlaikyti.' },
      food: { title: 'Maisto klausimai', blurb: 'Norai, gaminimas ir ginčai prie vakarienės stalo.' },
    },
    aboutH2: 'Kas yra Tralala?',
    aboutP1: 'Tralala — tai nemokamas pokalbių kortelių rinkinys, sukurtas paskatinti tikrus pokalbius, kurie eina toliau nei įprastas mandagumas. Nesvarbu, ar susitinki su senais draugais, gilini santykius, laužai ledus vakarėlyje, ar burinie komandą — Tralala visada paduoda kitą klausimą, kol dar neatsirado nejauki tyla.',
    aboutP2: 'Kiekvienu raundu gauni po vieną klausimą: perskaityk garsiai, perduok telefoną ratu ir stebėk, kur nuves pokalbis. Rinkis iš dešimties kategorijų — linksmi, gilūs, poroms, komandai, pažinties, aštrūs (18+), apie ateitį, pirmus kartus, nejaukūs ir apie maistą — arba sumaišyk viską į vieną kaladę. Klausimų vis daugėja, o kalbų yra šešios, tad visada atsiras kažkas naujo, ko paklausti.',
    aboutP3: 'Nieko diegti ar registruotis nereikia. Tralala veikia tiesiai naršyklėje, tinka bet kuriam telefonui ir įsimena tavo mėgstamiausius klausimus, kad vėliau galėtum jais pasidalinti. Tiesiog atsidaryk kaladę, pasirink savo nuotaiką ir pradėk kalbėtis.',
    forH2: 'Puikiai tinka',
    perfectFor: ['Draugai', 'Poros', 'Vakarėliai', 'Pasimatymai', 'Komandos', 'Kelionės'],
    ctaH2: 'Pasiruošęs pokalbiui?',
    ctaFine: 'Jokios paskyros. Jokio nustatymo. Tiesiog žaisk.',
    footer1: 'Tralala.cards — sukurta geresniems pokalbiams.',
    footer2: 'Renkami tik anoniminiai naudojimo duomenys — jokių paskyrų, jokių asmens duomenų.',
    footer3: 'Paspaudus „Pradėti“, sutinkama su anoniminių naudojimo duomenų rinkimu.',
  },

  de: {
    kicker: 'TRALALA',
    h2Line1: 'Gesprächskarten für',
    h2Line2: 'Freunde, Paare & Gruppen',
    lede: 'Von leichten Eisbrechern bis zu den Fragen, die du dir nie laut gestellt hast — finde unten deinen Vibe.',
    cta: 'Gespräch starten',
    introFine: 'Kostenlos starten. Kein Konto nötig.',
    vibesH2: 'Wähle deinen Vibe',
    vibes: {
      fun: { title: 'Lustige Fragen', blurb: 'Leichte, verspielte Fragen für Lacher mit allen.' },
      know: { title: 'Kennenlernfragen', blurb: 'Kennenlernfragen für neue Gesichter.' },
      deep: { title: 'Tiefgründige Fragen', blurb: 'Bedeutungsvolle Fragen jenseits von Smalltalk.' },
      team: { title: 'Team-Fragen', blurb: 'Eisbrecher für Kolleg:innen und Teams.' },
      spicy: { title: 'Pikante Fragen (18+)', blurb: 'Mutige, verspielte Fragen für die Tapferen (18+).' },
      future: { title: 'Zukunftsfragen', blurb: 'Träume, Ziele und was als Nächstes kommt.' },
      firsts: { title: 'Premierenfragen', blurb: 'Premieren, Erinnerungen und wie alles begann.' },
      awkward: { title: 'Peinliche Fragen', blurb: 'Geständnisse und Geschichten, die niemand kommen sah.' },
      couples: { title: 'Fragen für Paare', blurb: 'Gemacht für Date-Nights und Nähe.' },
      food: { title: 'Essensfragen', blurb: 'Gelüste, Kochen und Diskussionen am Esstisch.' },
    },
    aboutH2: 'Was ist Tralala?',
    aboutP1: 'Tralala ist ein kostenloses Set an Gesprächskarten, das echte Gespräche in Gang bringt — jenseits von Smalltalk. Ob du alte Freunde triffst, eine Beziehung vertiefst, auf einer Party das Eis brichst oder dein Team näher zusammenbringst: Tralala liefert dir die nächste Frage, bevor die Stille unangenehm wird.',
    aboutP2: 'Jede Runde bringt eine Frage zur Zeit: laut vorlesen, das Handy weiterreichen und schauen, wohin das Gespräch führt. Wähle aus zehn Kategorien — lustig, tiefgründig, für Paare, Team, Kennenlernen, pikant (18+), Zukunft, Premieren, peinlich und Essen — oder mische alles zu einem gemeinsamen Stapel. Das Kartenset wächst stetig und ist in sechs Sprachen verfügbar, es gibt also immer etwas Neues zu fragen.',
    aboutP3: 'Nichts zu installieren, nichts, wofür du dich anmelden musst. Tralala läuft komplett im Browser, funktioniert auf jedem Handy und merkt sich deine Lieblingsfragen, damit du sie später teilen kannst. Öffne einfach das Kartenset, wähle deinen Vibe und leg los.',
    forH2: 'Perfekt für',
    perfectFor: ['Freunde', 'Paare', 'Partys', 'Date-Nights', 'Teams', 'Roadtrips'],
    ctaH2: 'Bereit zu reden?',
    ctaFine: 'Kein Konto. Keine Einrichtung. Einfach spielen.',
    footer1: 'Tralala.cards — gemacht für bessere Gespräche.',
    footer2: 'Nur anonyme Nutzungsdaten — keine Konten, keine personenbezogenen Daten.',
    footer3: 'Mit dem Start stimmst du der Erhebung anonymer Nutzungsdaten zu.',
  },

  es: {
    kicker: 'TRALALA',
    h2Line1: 'Cartas de conversación para',
    h2Line2: 'amigos, parejas y grupos',
    lede: 'Desde preguntas ligeras para romper el hielo hasta las que nunca dijiste en voz alta: encuentra tu vibra abajo.',
    cta: 'Iniciar una conversación',
    introFine: 'Empieza gratis. No necesitas cuenta.',
    vibesH2: 'Elige tu vibra',
    vibes: {
      fun: { title: 'Preguntas divertidas', blurb: 'Preguntas ligeras y divertidas para reír con cualquiera.' },
      know: { title: 'Preguntas para conocerse', blurb: 'Preguntas para romper el hielo con caras nuevas.' },
      deep: { title: 'Preguntas profundas', blurb: 'Preguntas con sentido que van más allá de lo superficial.' },
      team: { title: 'Preguntas de equipo', blurb: 'Rompehielos para compañeros y equipos.' },
      spicy: { title: 'Preguntas picantes (18+)', blurb: 'Preguntas atrevidas para los valientes (18+).' },
      future: { title: 'Preguntas sobre el futuro', blurb: 'Sueños, metas y lo que viene después.' },
      firsts: { title: 'Preguntas sobre primeras veces', blurb: 'Primeras veces, recuerdos y cómo empezó todo.' },
      awkward: { title: 'Preguntas incómodas', blurb: 'Confesiones e historias que nadie vio venir.' },
      couples: { title: 'Preguntas para parejas', blurb: 'Pensadas para una noche de cita y estar más cerca.' },
      food: { title: 'Preguntas sobre comida', blurb: 'Antojos, cocina y debates de sobremesa.' },
    },
    aboutH2: '¿Qué es Tralala?',
    aboutP1: 'Tralala es un mazo gratuito de cartas de conversación pensado para provocar charlas de verdad, de las que van más allá de lo superficial. Ya sea que te estés poniendo al día con viejos amigos, profundizando una relación, rompiendo el hielo en una fiesta o uniendo a tu equipo, Tralala te da la siguiente pregunta antes de que el silencio se vuelva incómodo.',
    aboutP2: 'Cada ronda reparte una pregunta a la vez: léela en voz alta, pasa el teléfono y mira adónde va la conversación. Elige entre diez categorías —divertidas, profundas, para parejas, de equipo, para romper el hielo, picantes (18+), sobre el futuro, primeras veces, incómodas y sobre comida— o mézclalo todo en un mazo combinado. El mazo no deja de crecer y está disponible en seis idiomas, así que siempre hay algo nuevo que preguntar.',
    aboutP3: 'No hay nada que instalar ni que registrar. Tralala funciona directamente en tu navegador, funciona en cualquier teléfono y recuerda tus preguntas favoritas para que puedas compartirlas después. Solo abre el mazo, elige tu vibra y empieza a hablar.',
    forH2: 'Perfecto para',
    perfectFor: ['Amigos', 'Parejas', 'Fiestas', 'Citas', 'Equipos', 'Viajes por carretera'],
    ctaH2: '¿Listo para hablar?',
    ctaFine: 'Sin cuenta. Sin configuración. Solo juega.',
    footer1: 'Tralala.cards — hecho para mejores conversaciones.',
    footer2: 'Solo datos de uso anónimos — sin cuentas, sin datos personales.',
    footer3: 'Al empezar, aceptas la recopilación de datos de uso anónimos.',
  },

  it: {
    kicker: 'TRALALA',
    h2Line1: 'Carte per conversazioni con',
    h2Line2: 'amici, coppie e gruppi',
    lede: 'Da domande leggere per rompere il ghiaccio a quelle che non hai mai detto ad alta voce — trova il tuo mood qui sotto.',
    cta: 'Inizia una conversazione',
    introFine: 'Inizia gratis. Nessun account necessario.',
    vibesH2: 'Scegli il tuo mood',
    vibes: {
      fun: { title: 'Domande divertenti', blurb: 'Domande leggere e giocose per ridere con chiunque.' },
      know: { title: 'Domande per conoscersi', blurb: 'Domande per rompere il ghiaccio con facce nuove.' },
      deep: { title: 'Domande profonde', blurb: 'Domande che vanno oltre le chiacchiere superficiali.' },
      team: { title: 'Domande di squadra', blurb: 'Rompighiaccio per colleghi e squadre.' },
      spicy: { title: 'Domande piccanti (18+)', blurb: 'Domande audaci per i più coraggiosi (18+).' },
      future: { title: 'Domande sul futuro', blurb: 'Sogni, obiettivi e cosa viene dopo.' },
      firsts: { title: 'Domande sulle prime volte', blurb: 'Prime volte, ricordi e come è iniziato tutto.' },
      awkward: { title: 'Domande imbarazzanti', blurb: 'Confessioni e storie che nessuno si aspettava.' },
      couples: { title: 'Domande per coppie', blurb: 'Pensate per una serata romantica e per stare più vicini.' },
      food: { title: 'Domande sul cibo', blurb: 'Voglie, cucina e discussioni a tavola.' },
    },
    aboutH2: "Cos'è Tralala?",
    aboutP1: "Tralala è un mazzo gratuito di carte per conversazioni, pensato per accendere discorsi veri, di quelli che vanno oltre le chiacchiere di circostanza. Che tu stia recuperando il tempo perso con vecchi amici, approfondendo una relazione, rompendo il ghiaccio a una festa o rafforzando il tuo team, Tralala ti offre la prossima domanda prima che il silenzio diventi imbarazzante.",
    aboutP2: "Ogni round mette in gioco una domanda alla volta: leggila ad alta voce, passa il telefono e scopri dove va la conversazione. Scegli tra dieci categorie — divertenti, profonde, per coppie, di squadra, per conoscersi, piccanti (18+), sul futuro, sulle prime volte, imbarazzanti e sul cibo — oppure mescola tutto in un mazzo unico. Il mazzo continua a crescere ed è disponibile in sei lingue, quindi c'è sempre qualcosa di nuovo da chiedere.",
    aboutP3: "Non c'è niente da installare né alcuna registrazione. Tralala funziona interamente nel browser, va bene su qualsiasi telefono e ricorda le tue domande preferite così puoi condividerle più tardi. Apri semplicemente il mazzo, scegli il tuo mood e inizia a parlare.",
    forH2: 'Perfetto per',
    perfectFor: ['Amici', 'Coppie', 'Feste', 'Serate romantiche', 'Team', 'Viaggi on the road'],
    ctaH2: 'Pronto a parlare?',
    ctaFine: 'Nessun account. Nessuna configurazione. Si gioca e basta.',
    footer1: 'Tralala.cards — pensato per conversazioni migliori.',
    footer2: 'Solo dati di utilizzo anonimi — nessun account, nessun dato personale.',
    footer3: 'Iniziando, accetti la raccolta di dati di utilizzo anonimi.',
  },

  pl: {
    kicker: 'TRALALA',
    h2Line1: 'Karty do rozmów dla',
    h2Line2: 'przyjaciół, par i grup',
    lede: 'Od lekkich pytań na przełamanie lodów po te, których nigdy nie powiedziałeś na głos — znajdź swój klimat poniżej.',
    cta: 'Rozpocznij rozmowę',
    introFine: 'Zacznij za darmo. Konto niepotrzebne.',
    vibesH2: 'Wybierz swój klimat',
    vibes: {
      fun: { title: 'Zabawne pytania', blurb: 'Lekkie, zabawne pytania do śmiechu z każdym.' },
      know: { title: 'Pytania na przełamanie lodów', blurb: 'Pytania na przełamanie lodów z nowymi osobami.' },
      deep: { title: 'Głębokie pytania', blurb: 'Pytania, które wychodzą poza zwykłą rozmowę.' },
      team: { title: 'Pytania dla zespołu', blurb: 'Pytania na przełamanie lodów dla współpracowników i zespołów.' },
      spicy: { title: 'Pikantne pytania (18+)', blurb: 'Odważne, pikantne pytania dla śmiałków (18+).' },
      future: { title: 'Pytania o przyszłość', blurb: 'Marzenia, cele i to, co dalej.' },
      firsts: { title: 'Pytania o pierwsze razy', blurb: 'Pierwsze razy, wspomnienia i jak to się zaczęło.' },
      awkward: { title: 'Niezręczne pytania', blurb: 'Wyznania i historie, których nikt się nie spodziewał.' },
      couples: { title: 'Pytania dla par', blurb: 'Stworzone na randkę i budowanie bliskości.' },
      food: { title: 'Pytania o jedzenie', blurb: 'Zachcianki, gotowanie i dyskusje przy stole.' },
    },
    aboutH2: 'Czym jest Tralala?',
    aboutP1: 'Tralala to darmowy zestaw kart do rozmów, stworzony po to, by wywoływać prawdziwe rozmowy — takie, które wychodzą poza uprzejmą pogawędkę. Niezależnie od tego, czy nadrabiasz zaległości ze starymi znajomymi, pogłębiasz relację, przełamujesz lody na imprezie, czy integrujesz zespół — Tralala zawsze poda kolejne pytanie, zanim zapadnie niezręczna cisza.',
    aboutP2: 'Każda runda to jedno pytanie na raz: przeczytaj je na głos, podaj telefon dalej i zobacz, dokąd zaprowadzi was rozmowa. Wybieraj spośród dziesięciu kategorii — zabawne, głębokie, dla par, dla zespołu, na przełamanie lodów, pikantne (18+), o przyszłości, o pierwszych razach, niezręczne i o jedzeniu — albo wymieszaj wszystko w jedną talię. Talia wciąż się powiększa i jest dostępna w sześciu językach, więc zawsze znajdzie się coś nowego do zapytania.',
    aboutP3: 'Nie musisz nic instalować ani zakładać konta. Tralala działa całkowicie w przeglądarce, działa na każdym telefonie i zapamiętuje twoje ulubione pytania, żebyś mógł się nimi później podzielić. Po prostu otwórz talię, wybierz swój klimat i zacznij rozmawiać.',
    forH2: 'Idealne na',
    perfectFor: ['Przyjaciele', 'Pary', 'Imprezy', 'Randki', 'Zespoły', 'Podróże samochodem'],
    ctaH2: 'Gotowy na rozmowę?',
    ctaFine: 'Bez konta. Bez konfiguracji. Po prostu graj.',
    footer1: 'Tralala.cards — stworzone dla lepszych rozmów.',
    footer2: 'Tylko anonimowe dane o użytkowaniu — bez kont, bez danych osobowych.',
    footer3: 'Rozpoczynając, zgadzasz się na zbieranie anonimowych danych o użytkowaniu.',
  },
};
