// Marketing copy for the landing sections below the game (app/LandingContent.jsx,
// app/LandingFooter.jsx). Kept separate from lib/content.js, which is the game's
// own question/UI-string data. Vibe entries are keyed by the same category ids
// as CATEGORIES in lib/content.js.

export const LANDING = {
  en: {
    kicker: 'TRALALA',
    h2Line1: 'Conversation Cards for',
    h2Line2: 'Friends, Couples & Groups',
    lede: "Some questions are easy icebreakers. Others are the ones you've never said out loud. Pick a deck and start.",
    cta: 'Start a Conversation',
    introFine: "Free to play. No account needed.",
    vibesH2: "Choose your vibe",
    vibes: {
      fun: { title: 'Fun Questions', blurb: 'Light, playful prompts for laughs with anyone.' },
      know: { title: 'Icebreaker Questions', blurb: 'Get-to-know-you icebreakers for new faces.' },
      deep: { title: 'Deep Questions', blurb: 'Meaningful questions that go past small talk.' },
      team: { title: 'Team Questions', blurb: 'Icebreakers built for coworkers and teammates.' },
      spicy: { title: 'Spicy Questions', blurb: 'Bold, flirty questions for the brave (18+).' },
      future: { title: 'Future Questions', blurb: 'Dreams, goals and what comes next.' },
      firsts: { title: 'Firsts Questions', blurb: 'Firsts, memories and how it all began.' },
      awkward: { title: 'Awkward Questions', blurb: 'Confessions and stories nobody saw coming.' },
      couples: { title: 'Couples Questions', blurb: 'Built for date night and staying close.' },
      food: { title: 'Food Questions', blurb: 'Cravings, cooking and dinner-table debates.' },
    },
    aboutH2: "What is Tralala?",
    aboutP1: "Tralala is a free deck of conversation cards for friends, couples, parties and teams. It hands you the next question before the silence gets awkward.",
    aboutP2: "The app shows one question at a time. Read it out loud, pass the phone and see where the talk goes. There are ten decks: fun, deep, couples, team, icebreakers, spicy (18+), future, firsts, awkward and food. You can also play all of them mixed together. Every card is available in six languages, and we keep adding new ones.",
    aboutP3: "No download and no account needed. Tralala runs in your browser on any phone, and you can add it to your home screen like an app. Star a question you like and it stays in Saved, ready to share later.",
    samplesH2: "Sample questions from each deck",
    samplesPlay: "Play this deck",
    faqH2: "Frequently asked questions",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Is Tralala free?", "Yes. Every deck and every card is free to play, with no account or sign-up."],
      ["How do you play?", "Open Tralala on one phone and pick a deck. Read the question out loud, let everyone answer, then tap the card or press Next and pass the phone on."],
      ["How many people can play?", "As many as you like, from two people on a date night to a big group at a party or a team meeting. You only need one phone."],
      ["Which languages is it in?", "English, Lithuanian, German, Spanish, Italian and Polish. You can switch language at any time."],
      ["Do I need to download an app?", "No. Tralala runs in the browser on any phone. On iPhone or Android you can add it to your home screen so it opens like an app."],
      ["Is there an 18+ deck?", "Yes. The Spicy deck is for adults only (18+), and you choose how far it goes: Mild, Spicy or No mercy. Every other deck works for any group."],
    ],
    ctaH2: "Ready to talk?",
    ctaFine: "No account or setup needed.",
    footer1: "Tralala.cards, made for better conversations.",
    footer2: "We only collect anonymous usage data. No accounts, no personal data.",
    footer3: 'By starting, you agree to anonymous usage data being collected.',
  },

  lt: {
    kicker: 'TRALALA',
    h2Line1: 'Pokalbių kortelės',
    h2Line2: 'draugams, poroms ir grupėms',
    lede: "Vieni klausimai lengvi, pažinčiai. Kiti tokie, kurių niekada nesakei garsiai. Pasirink kaladę ir pradėk.",
    cta: 'Pradėti pokalbį',
    introFine: 'Pradėk nemokamai. Paskyra nereikalinga.',
    vibesH2: 'Pasirink savo nuotaiką',
    vibes: {
      fun: { title: 'Linksmi klausimai', blurb: 'Lengvi, žaismingi klausimai juokui su bet kuo.' },
      know: { title: 'Pažinties klausimai', blurb: 'Pažinties klausimai naujiems veidams.' },
      deep: { title: 'Gilūs klausimai', blurb: 'Prasmingi klausimai, einantys giliau nei buitinis pokalbis.' },
      team: { title: 'Komandos klausimai', blurb: 'Įžanginiai klausimai kolegoms ir komandai.' },
      spicy: { title: 'Aštrūs klausimai (18+)', blurb: 'Drąsūs, flirtuojantys klausimai drąsiems (18+).' },
      future: { title: 'Ateities klausimai', blurb: 'Svajonės, tikslai ir kas laukia toliau.' },
      firsts: { title: 'Pirmų kartų klausimai', blurb: 'Pirmi kartai, prisiminimai ir kaip viskas prasidėjo.' },
      awkward: { title: 'Nejaukūs klausimai', blurb: 'Prisipažinimai ir istorijos, kurių niekas nesitikėjo.' },
      couples: { title: 'Klausimai poroms', blurb: 'Sukurta pasimatymo vakarui ir artumui išlaikyti.' },
      food: { title: 'Maisto klausimai', blurb: 'Norai, gaminimas ir ginčai prie vakarienės stalo.' },
    },
    aboutH2: 'Kas yra Tralala?',
    aboutP1: "Tralala yra nemokamas pokalbių kortelių rinkinys draugams, poroms, vakarėliams ir komandoms. Kitas klausimas atsiranda anksčiau, nei spėja stoti nejauki tyla.",
    aboutP2: "Programėlė rodo po vieną klausimą. Perskaityk jį garsiai, perduok telefoną ir pažiūrėk, kur nuves pokalbis. Kaladžių yra dešimt: linksmi, gilūs, poroms, komandai, pažinties, aštrūs (18+), ateitis, pirmi kartai, nejaukūs ir maistas. Galima žaisti ir visas kartu. Visi klausimai yra šešiomis kalbomis, o naujų vis pridedame.",
    aboutP3: "Nieko atsisiųsti ir registruotis nereikia. Tralala veikia naršyklėje, bet kuriame telefone, o jei nori, gali ją įsidėti į pradžios ekraną kaip programėlę. Patikusį klausimą pažymėk žvaigždute: jis liks skiltyje „Išsaugoti“, ir vėliau galėsi juo pasidalinti.",
    samplesH2: "Klausimų pavyzdžiai iš kiekvienos kaladės",
    samplesPlay: "Žaisti šią kaladę",
    faqH2: "Dažniausi klausimai",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Ar Tralala nemokama?", "Taip. Visos kaladės ir kortelės nemokamos, be paskyros ir registracijos."],
      ["Kaip žaisti?", "Atsidaryk Tralala viename telefone ir pasirink kaladę. Garsiai perskaityk klausimą, leisk visiems atsakyti, tada bakstelėk kortelę arba „Kita“ ir perduok telefoną toliau."],
      ["Kiek žmonių gali žaisti?", "Kiek tik norite: nuo dviejų per pasimatymą iki didelės kompanijos vakarėlyje ar komandos susitikime. Užtenka vieno telefono."],
      ["Kokiomis kalbomis galima žaisti?", "Anglų, lietuvių, vokiečių, ispanų, italų ir lenkų. Kalbą gali pakeisti bet kada."],
      ["Ar reikia atsisiųsti programėlę?", "Ne. Tralala veikia bet kurio telefono naršyklėje. „iPhone“ ar „Android“ telefone ją gali įsidėti į pradžios ekraną, kad atsidarytų kaip programėlė."],
      ["Ar yra kaladė suaugusiems?", "Taip. „Aštrūs“ klausimai skirti tik suaugusiems (18+), o aštrumą renkiesi tu: švelniai, aštriai arba be gailesčio. Visos kitos kaladės tinka bet kuriai kompanijai."],
    ],
    ctaH2: 'Pasiruošęs pokalbiui?',
    ctaFine: "Paskyros ir nustatymų nereikia.",
    footer1: "Tralala.cards, sukurta geresniems pokalbiams.",
    footer2: "Renkame tik anoniminius naudojimo duomenis. Jokių paskyrų, jokių asmens duomenų.",
    footer3: 'Paspaudus „Pradėti“, sutinkama su anoniminių naudojimo duomenų rinkimu.',
  },

  de: {
    kicker: 'TRALALA',
    h2Line1: 'Gesprächskarten für',
    h2Line2: 'Freunde, Paare & Gruppen',
    lede: "Manche Fragen brechen locker das Eis. Andere hast du noch nie laut ausgesprochen. Wähl ein Deck und leg los.",
    cta: 'Gespräch starten',
    introFine: 'Kostenlos starten. Kein Konto nötig.',
    vibesH2: 'Wähle deinen Vibe',
    vibes: {
      fun: { title: 'Lustige Fragen', blurb: 'Leichte, verspielte Fragen für Lacher mit allen.' },
      know: { title: 'Kennenlernfragen', blurb: 'Kennenlernfragen für neue Gesichter.' },
      deep: { title: 'Tiefgründige Fragen', blurb: 'Bedeutungsvolle Fragen jenseits von Smalltalk.' },
      team: { title: 'Team-Fragen', blurb: 'Eisbrecher für Kolleg:innen und Teams.' },
      spicy: { title: 'Pikante Fragen (18+)', blurb: 'Mutige, verspielte Fragen für die Tapferen (18+).' },
      future: { title: 'Zukunftsfragen', blurb: 'Träume, Ziele und was als Nächstes kommt.' },
      firsts: { title: 'Premierenfragen', blurb: 'Premieren, Erinnerungen und wie alles begann.' },
      awkward: { title: 'Peinliche Fragen', blurb: 'Geständnisse und Geschichten, die niemand kommen sah.' },
      couples: { title: 'Fragen für Paare', blurb: 'Gemacht für Date-Nights und Nähe.' },
      food: { title: 'Essensfragen', blurb: 'Gelüste, Kochen und Diskussionen am Esstisch.' },
    },
    aboutH2: 'Was ist Tralala?',
    aboutP1: "Tralala ist ein kostenloses Set Gesprächskarten für Freunde, Paare, Partys und Teams. Es liefert dir die nächste Frage, bevor die Stille unangenehm wird.",
    aboutP2: "Die App zeigt eine Frage nach der anderen. Lies sie laut vor, gib das Handy weiter und schau, wohin das Gespräch führt. Es gibt zehn Decks: lustig, tiefgründig, für Paare, Team, Kennenlernen, pikant (18+), Zukunft, Premieren, peinlich und Essen. Du kannst auch alle gemischt spielen. Jede Karte gibt es in sechs Sprachen, und wir fügen laufend neue hinzu.",
    aboutP3: "Kein Download, kein Konto. Tralala läuft im Browser auf jedem Handy, und du kannst es wie eine App auf deinen Home-Bildschirm legen. Markier eine Frage mit einem Stern, dann bleibt sie unter „Gespeichert“ und du kannst sie später teilen.",
    samplesH2: "Beispielfragen aus jedem Deck",
    samplesPlay: "Dieses Deck spielen",
    faqH2: "Häufige Fragen",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Ist Tralala kostenlos?", "Ja. Alle Decks und Karten sind kostenlos, ohne Konto und ohne Anmeldung."],
      ["Wie spielt man?", "Öffne Tralala auf einem Handy und wähle ein Deck. Lies die Frage laut vor, lass alle antworten, tippe dann auf die Karte oder auf „Weiter“ und gib das Handy weiter."],
      ["Wie viele können mitspielen?", "So viele ihr wollt: vom Date zu zweit bis zur großen Runde auf einer Party oder im Team-Meeting. Ihr braucht nur ein Handy."],
      ["In welchen Sprachen gibt es Tralala?", "Englisch, Litauisch, Deutsch, Spanisch, Italienisch und Polnisch. Du kannst die Sprache jederzeit wechseln."],
      ["Muss ich eine App herunterladen?", "Nein. Tralala läuft im Browser auf jedem Handy. Auf dem iPhone oder Android-Handy kannst du es auf den Home-Bildschirm legen, dann öffnet es sich wie eine App."],
      ["Gibt es ein Deck ab 18?", "Ja. Das Deck „Pikant“ ist nur für Erwachsene (18+), und du bestimmst, wie weit es geht: Mild, Scharf oder Gnadenlos. Alle anderen Decks passen für jede Runde."],
    ],
    ctaH2: 'Bereit zu reden?',
    ctaFine: "Kein Konto, keine Einrichtung nötig.",
    footer1: "Tralala.cards, gemacht für bessere Gespräche.",
    footer2: "Wir erheben nur anonyme Nutzungsdaten. Keine Konten, keine personenbezogenen Daten.",
    footer3: 'Mit dem Start stimmst du der Erhebung anonymer Nutzungsdaten zu.',
  },

  es: {
    kicker: 'TRALALA',
    h2Line1: 'Cartas de conversación para',
    h2Line2: 'amigos, parejas y grupos',
    lede: "Hay preguntas fáciles para romper el hielo. Otras son las que nunca has dicho en voz alta. Elige una baraja y empieza.",
    cta: 'Iniciar una conversación',
    introFine: 'Empieza gratis. No necesitas cuenta.',
    vibesH2: 'Elige tu vibra',
    vibes: {
      fun: { title: 'Preguntas divertidas', blurb: 'Preguntas ligeras y divertidas para reír con cualquiera.' },
      know: { title: 'Preguntas para conocerse', blurb: 'Preguntas para romper el hielo con caras nuevas.' },
      deep: { title: 'Preguntas profundas', blurb: 'Preguntas con sentido que van más allá de lo superficial.' },
      team: { title: 'Preguntas de equipo', blurb: 'Rompehielos para compañeros y equipos.' },
      spicy: { title: 'Preguntas picantes (18+)', blurb: 'Preguntas atrevidas para los valientes (18+).' },
      future: { title: 'Preguntas sobre el futuro', blurb: 'Sueños, metas y lo que viene después.' },
      firsts: { title: 'Preguntas sobre primeras veces', blurb: 'Primeras veces, recuerdos y cómo empezó todo.' },
      awkward: { title: 'Preguntas incómodas', blurb: 'Confesiones e historias que nadie vio venir.' },
      couples: { title: 'Preguntas para parejas', blurb: 'Pensadas para una noche de cita y estar más cerca.' },
      food: { title: 'Preguntas sobre comida', blurb: 'Antojos, cocina y debates de sobremesa.' },
    },
    aboutH2: '¿Qué es Tralala?',
    aboutP1: "Tralala es una baraja gratuita de cartas de conversación para amigos, parejas, fiestas y equipos. Te da la siguiente pregunta antes de que el silencio se vuelva incómodo.",
    aboutP2: "La app muestra una pregunta cada vez. Léela en voz alta, pasa el teléfono y mira adónde va la conversación. Hay diez barajas: divertidas, profundas, para parejas, de equipo, para romper el hielo, picantes (18+), futuro, primeras veces, incómodas y comida. También puedes jugarlas todas mezcladas. Todas las cartas están en seis idiomas y seguimos añadiendo nuevas.",
    aboutP3: "Sin descargas ni cuentas. Tralala funciona en el navegador de cualquier teléfono y puedes añadirla a tu pantalla de inicio como una app. Marca con una estrella la pregunta que te guste y se quedará en Guardadas, lista para compartir después.",
    samplesH2: "Preguntas de ejemplo de cada baraja",
    samplesPlay: "Jugar esta baraja",
    faqH2: "Preguntas frecuentes",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["¿Tralala es gratis?", "Sí. Todas las barajas y cartas son gratis, sin cuenta ni registro."],
      ["¿Cómo se juega?", "Abre Tralala en un móvil y elige una baraja. Lee la pregunta en voz alta, deja que todos respondan y luego toca la carta o «Siguiente» y pasa el móvil."],
      ["¿Cuántas personas pueden jugar?", "Las que queráis: desde dos en una cita hasta un grupo grande en una fiesta o una reunión de equipo. Solo necesitáis un móvil."],
      ["¿En qué idiomas está?", "Inglés, lituano, alemán, español, italiano y polaco. Puedes cambiar de idioma cuando quieras."],
      ["¿Hay que descargar una app?", "No. Tralala funciona en el navegador de cualquier teléfono. En iPhone o Android puedes añadirla a la pantalla de inicio y se abrirá como una app."],
      ["¿Hay una baraja para mayores de 18?", "Sí. La baraja «Picantes» es solo para adultos (18+) y tú eliges hasta dónde llega: Suave, Picante o Sin piedad. Todas las demás barajas sirven para cualquier grupo."],
    ],
    ctaH2: '¿Listo para hablar?',
    ctaFine: "Sin cuenta ni configuración.",
    footer1: "Tralala.cards, hecho para mejores conversaciones.",
    footer2: "Solo recogemos datos de uso anónimos. Sin cuentas ni datos personales.",
    footer3: 'Al empezar, aceptas la recopilación de datos de uso anónimos.',
  },

  it: {
    kicker: 'TRALALA',
    h2Line1: 'Carte per conversazioni con',
    h2Line2: 'amici, coppie e gruppi',
    lede: "Alcune domande rompono il ghiaccio con leggerezza. Altre sono quelle che non hai mai detto ad alta voce. Scegli un mazzo e inizia.",
    cta: 'Inizia una conversazione',
    introFine: 'Inizia gratis. Nessun account necessario.',
    vibesH2: 'Scegli il tuo mood',
    vibes: {
      fun: { title: 'Domande divertenti', blurb: 'Domande leggere e giocose per ridere con chiunque.' },
      know: { title: 'Domande per conoscersi', blurb: 'Domande per rompere il ghiaccio con facce nuove.' },
      deep: { title: 'Domande profonde', blurb: 'Domande che vanno oltre le chiacchiere superficiali.' },
      team: { title: 'Domande di squadra', blurb: 'Rompighiaccio per colleghi e squadre.' },
      spicy: { title: 'Domande piccanti (18+)', blurb: 'Domande audaci per i più coraggiosi (18+).' },
      future: { title: 'Domande sul futuro', blurb: 'Sogni, obiettivi e cosa viene dopo.' },
      firsts: { title: 'Domande sulle prime volte', blurb: 'Prime volte, ricordi e come è iniziato tutto.' },
      awkward: { title: 'Domande imbarazzanti', blurb: 'Confessioni e storie che nessuno si aspettava.' },
      couples: { title: 'Domande per coppie', blurb: 'Pensate per una serata romantica e per stare più vicini.' },
      food: { title: 'Domande sul cibo', blurb: 'Voglie, cucina e discussioni a tavola.' },
    },
    aboutH2: "Cos'è Tralala?",
    aboutP1: "Tralala è un mazzo gratuito di carte per conversazioni tra amici, coppie, feste e team. Ti dà la prossima domanda prima che il silenzio diventi imbarazzante.",
    aboutP2: "L'app mostra una domanda alla volta. Leggila ad alta voce, passa il telefono e guarda dove va la conversazione. Ci sono dieci mazzi: divertenti, profonde, per coppie, di squadra, per conoscersi, piccanti (18+), futuro, prime volte, imbarazzanti e cibo. Puoi anche giocarli tutti insieme. Ogni carta è disponibile in sei lingue e ne aggiungiamo sempre di nuove.",
    aboutP3: "Niente download e nessun account. Tralala funziona nel browser di qualsiasi telefono e puoi aggiungerla alla schermata Home come un'app. Segna con una stella la domanda che ti piace: resta tra le Salvate, pronta da condividere più tardi.",
    samplesH2: "Domande di esempio da ogni mazzo",
    samplesPlay: "Gioca questo mazzo",
    faqH2: "Domande frequenti",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Tralala è gratis?", "Sì. Tutti i mazzi e tutte le carte sono gratis, senza account e senza registrazione."],
      ["Come si gioca?", "Apri Tralala su un telefono e scegli un mazzo. Leggi la domanda ad alta voce, lascia rispondere tutti, poi tocca la carta o «Avanti» e passa il telefono."],
      ["Quante persone possono giocare?", "Quante volete: da due a un appuntamento fino a un gruppo numeroso a una festa o a una riunione di team. Basta un telefono."],
      ["In quali lingue è disponibile?", "Inglese, lituano, tedesco, spagnolo, italiano e polacco. Puoi cambiare lingua quando vuoi."],
      ["Devo scaricare un'app?", "No. Tralala funziona nel browser di qualsiasi telefono. Su iPhone o Android puoi aggiungerla alla schermata Home e si aprirà come un'app."],
      ["C'è un mazzo per adulti?", "Sì. Il mazzo «Piccanti» è solo per adulti (18+) e scegli tu fin dove arrivare: Leggero, Piccante o Senza pietà. Tutti gli altri mazzi vanno bene per qualsiasi gruppo."],
    ],
    ctaH2: 'Pronto a parlare?',
    ctaFine: "Nessun account né configurazione.",
    footer1: "Tralala.cards, pensato per conversazioni migliori.",
    footer2: "Raccogliamo solo dati di utilizzo anonimi. Nessun account, nessun dato personale.",
    footer3: 'Iniziando, accetti la raccolta di dati di utilizzo anonimi.',
  },

  pl: {
    kicker: 'TRALALA',
    h2Line1: 'Karty do rozmów dla',
    h2Line2: 'przyjaciół, par i grup',
    lede: "Niektóre pytania lekko przełamują lody. Inne to te, których nigdy nie powiedziałeś na głos. Wybierz talię i zaczynaj.",
    cta: 'Rozpocznij rozmowę',
    introFine: 'Zacznij za darmo. Konto niepotrzebne.',
    vibesH2: 'Wybierz swój klimat',
    vibes: {
      fun: { title: 'Zabawne pytania', blurb: 'Lekkie, zabawne pytania do śmiechu z każdym.' },
      know: { title: 'Pytania na przełamanie lodów', blurb: 'Pytania na przełamanie lodów z nowymi osobami.' },
      deep: { title: 'Głębokie pytania', blurb: 'Pytania, które wychodzą poza zwykłą rozmowę.' },
      team: { title: 'Pytania dla zespołu', blurb: 'Pytania na przełamanie lodów dla współpracowników i zespołów.' },
      spicy: { title: 'Pikantne pytania (18+)', blurb: 'Odważne, pikantne pytania dla śmiałków (18+).' },
      future: { title: 'Pytania o przyszłość', blurb: 'Marzenia, cele i to, co dalej.' },
      firsts: { title: 'Pytania o pierwsze razy', blurb: 'Pierwsze razy, wspomnienia i jak to się zaczęło.' },
      awkward: { title: 'Niezręczne pytania', blurb: 'Wyznania i historie, których nikt się nie spodziewał.' },
      couples: { title: 'Pytania dla par', blurb: 'Stworzone na randkę i budowanie bliskości.' },
      food: { title: 'Pytania o jedzenie', blurb: 'Zachcianki, gotowanie i dyskusje przy stole.' },
    },
    aboutH2: 'Czym jest Tralala?',
    aboutP1: "Tralala to darmowy zestaw kart do rozmów dla przyjaciół, par, imprez i zespołów. Podaje kolejne pytanie, zanim zapadnie niezręczna cisza.",
    aboutP2: "Aplikacja pokazuje jedno pytanie naraz. Przeczytaj je na głos, podaj telefon dalej i zobacz, dokąd zaprowadzi was rozmowa. Jest dziesięć talii: zabawne, głębokie, dla par, dla zespołu, na przełamanie lodów, pikantne (18+), przyszłość, pierwsze razy, niezręczne i jedzenie. Możesz też grać wszystkimi naraz. Każda karta jest w sześciu językach, a nowe wciąż dodajemy.",
    aboutP3: "Bez pobierania i bez konta. Tralala działa w przeglądarce na każdym telefonie, a jeśli chcesz, dodasz ją do ekranu początkowego jak aplikację. Oznacz gwiazdką pytanie, które ci się podoba, a zostanie w Zapisanych, gotowe do udostępnienia.",
    samplesH2: "Przykładowe pytania z każdej talii",
    samplesPlay: "Zagraj tą talią",
    faqH2: "Najczęstsze pytania",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Czy Tralala jest darmowa?", "Tak. Wszystkie talie i karty są darmowe, bez konta i rejestracji."],
      ["Jak się gra?", "Otwórz Tralalę na jednym telefonie i wybierz talię. Przeczytaj pytanie na głos, niech wszyscy odpowiedzą, potem stuknij kartę albo „Dalej” i podaj telefon dalej."],
      ["Ile osób może grać?", "Ile chcecie: od dwóch osób na randce po dużą grupę na imprezie albo spotkaniu zespołu. Wystarczy jeden telefon."],
      ["W jakich językach jest dostępna?", "Angielski, litewski, niemiecki, hiszpański, włoski i polski. Język możesz zmienić w każdej chwili."],
      ["Czy trzeba pobierać aplikację?", "Nie. Tralala działa w przeglądarce na każdym telefonie. Na iPhonie lub Androidzie możesz dodać ją do ekranu początkowego, żeby otwierała się jak aplikacja."],
      ["Czy jest talia dla dorosłych?", "Tak. Talia „Pikantne” jest tylko dla dorosłych (18+), a poziom wybierasz ty: Łagodnie, Pikantnie albo Bez litości. Pozostałe talie pasują do każdej grupy."],
    ],
    ctaH2: 'Gotowy na rozmowę?',
    ctaFine: "Bez konta i konfiguracji.",
    footer1: "Tralala.cards, stworzone dla lepszych rozmów.",
    footer2: "Zbieramy tylko anonimowe dane o użytkowaniu. Bez kont i danych osobowych.",
    footer3: 'Rozpoczynając, zgadzasz się na zbieranie anonimowych danych o użytkowaniu.',
  },
};
